#!/bin/sh
{
  echo "You are on $(hostname) running kernel $(uname -r) for $(uname -m)"
  echo "It is currently $(date '+%Y-%m-%d %H:%M:%S') and you are on tty \\l"
  echo "Thanks for using ObsidianOS!"
  echo
  obsidianctl status 2>/dev/null || echo "(obsidianctl not available)"
} > /run/issue
